import tkinter as tk


########################### BACKUP PAGE ###############################

class backup(tk.Frame):

    def __init__(self, parent, controller):
        self.controller = controller
        tk.Frame.__init__(self, parent, bg=controller.bgColor[0], highlightbackground="black", highlightthickness=1)
        self.controller = controller
        head = tk.Label(self, bg=controller.bgColor[0], fg=controller.bgColor[1], text="BACKUP",
                        font=controller.heading)
        expBut = tk.Button(self,
                           bg=controller.bgColor[1], fg='#343434',
                           text='EXPORT', font=controller.but,
                           command=lambda: print("Export"),
                           activebackground=controller.bgColor[2],
                           relief=tk.SOLID,
                           borderwidth=0,
                           padx=16, pady=7, cursor="hand2")
        impBut = tk.Button(self,
                           bg=controller.bgColor[1], fg='#343434',
                           text='IMPORT', font=controller.but,
                           command=lambda: print("Import"),
                           activebackground=controller.bgColor[2],
                           relief=tk.SOLID,
                           borderwidth=0,
                           padx=16, pady=7, cursor="hand2")
        note1 = tk.Label(self, bg=controller.bgColor[0], fg=controller.bgColor[1], text="1", font=controller.notesBig)
        note2 = tk.Label(self, bg=controller.bgColor[0], fg=controller.bgColor[1], text="2", font=controller.notesBig)
        note3 = tk.Label(self, bg=controller.bgColor[0], fg=controller.bgColor[1],
                         text="Exports will be in \nEncrytion Format\n\nImport file must be the\nfile generated by\nthis software",
                         font=controller.notesBig,
                         justify=tk.LEFT,
                         bd=0.5, relief=tk.SOLID,
                         padx=15, pady=15)

        head.place(relx=0.5, rely=0.1, y=50, anchor=tk.CENTER)
        expBut.place(relx=0.5, rely=0.3, y=80, anchor=tk.CENTER, width=190, height=36)
        impBut.place(relx=0.5, rely=0.3, y=180, anchor=tk.CENTER, width=190, height=36)
        note1.place(relx=0.4, rely=0.3, y=80, x=-30, anchor=tk.CENTER)
        note2.place(relx=0.4, rely=0.3, y=180, x=-30, anchor=tk.CENTER)
        note3.place(relx=0.15, rely=0.87, anchor=tk.CENTER)
        controller.homeButton(self)
        controller.exitButton(self)

    ### KEY BINDS ###
    def binds(self):
        self.controller.bind('1', lambda x: print("Import"))
        self.controller.bind('2', lambda x: print("Export"))
